### PR TITLE
update MSBuild solution to Windows SDK v10.0, add inet_pton define (fixes #5856)

### LINKED ISSUE #5856: 'LightGBM:inet_pton': ambiguous call to overloaded function (compiling source file ..\src\network\liners_socket.app)
Hi James,

I am still facing the same issue despite using the sln file from v 3.3.5 uploaded on January 23rd. (https://github.com/microsoft/LightGBM/releases). I have selected Windows SDK 10.0 (latest installed version) and Visual Studio 2022(v143) under general properties. See error log below.
          
Screenshot 2023-04-25 121916

"Thanks for your interest in LightGBM!

I put some of the text of those logs through Google Translate (I cannot read the language they're in, apologies), and saw that it looks like you are hitting this during compilation:

> error C2668: "LightGBM::inet_pton": ambiguous call to overloaded function (compile source file..\src\network \linkers_socket.cpp)

LightGBM has its own implementation of `inet_pton`, but some newer compilers on Windows ship with their own, conflicting implementation.

If you searched this project's issue tracker for that error message, you'd see that the same error was reported in #5019, and fixed about 5 months ago in #5159.

Please update to a newer version of LightGBM's source code, from at least after #5159.

If that doesn't resolve the issue you're facing, please click below to see the information we need to efficiently, effectively help you.

<details><summary>how to ask for help (click me)</summary>

It is very very very difficult for maintainers to help you when you only report a wall of logs without other context.

* are you installing the Python package / R package? just building the CLI? something else?
* how did you try to install LightGBM?
* what version are you using?
* it seems like you might be using Visual Studio to compile LightGBM... what version of Visual Studio? Did you customize anything about the installation?

Without answers like this, you are asking maintainers here to guess what you're doing, and that will take away our already-limited time from other work on this project.

Can you please provide the answers to the questions I've asked above?

</details>

_Originally posted by @jameslamb in https://github.com/microsoft/LightGBM/issues/5499#issuecomment-1271827484_"

### PR DESCRIPTION
**Pull request by jameslamb**
Fixes #5856.
Contributes to #5061.

Tonight I tried compiling LightGBM on latest `master` with `MSBUild` (using Visual Studio 2019), like this:

```pwsh
MSBuild.exe windows/LightGBM.sln /p:Configuration=DLL /p:Platform=x64 /p:PlatformToolset=v142
```

That resulted in this error:

>   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\cstddef(12,10): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory (compiling source file ..\src\treelearner\voting_parallel_tree_learner.cpp) [C:\Users\James\repos\LightGBM\windows\LightGBM.vcxproj]

Updating the target Windows SDK version from 8.1 to 10.0 fixed that.

Then I hit the error reported in #5856. I think that happened because when building without CMake, the test introduced in #5159 isn't run, `WIN_HAS_INET_PTON` isn't defined, and then the implementation in `socket_wrapper.hpp` conflicts with the one linked in from ws2_32.

This PR proposes always defining that in the `MSBuild` configuration, since it should be only older releases of MinGW that didn't have a definition for that function.

### How I tested this

Ran that command from above on this branch, using Visual Studio 2019 on Windows 10.

Saw that LightGBM compiled successfully.

### CODE REVIEW

**Comment by jameslamb** [comment]
Could I please get a review on this?

**Review by guolinke — APPROVED** [review]
