### ISSUE TITLE
plot_tree and create_tree_digraph doesn't work

### ISSUE THREAD

**Issue by Twinkle123321** [Microsoft/LightGBM#1844]
when I run graph = lgb.create_tree_digraph(clf2,tree_index=1),it shows as follows,I pip install graphviz and add graphviz‘'s bin into system path,however it still doesn't work,would some one help me?thanks very much!
Traceback (most recent call last):

  File "<ipython-input-57-f001bc6e1e7e>", line 1, in <module>
    graph = lgb.create_tree_digraph(clf2,tree_index=1)

  File "C:\Users\Guo\Anaconda3\lib\site-packages\lightgbm\plotting.py", line 382, in create_tree_digraph
    node_attr=node_attr, edge_attr=edge_attr, body=body, strict=strict)

  File "C:\Users\Guo\Anaconda3\lib\site-packages\lightgbm\plotting.py", line 302, in _to_graphviz
    node_attr=node_attr, edge_attr=edge_attr, body=body, strict=strict)

TypeError: __init__() got an unexpected keyword argument 'strict'

**Comment by Twinkle123321** [comment]
thank you very much,I have installed binaries of Graphviz,and used the latest version of LightGBM (2.2.2).
when I run lgb.plot_tree(clf)    it still dosen't work and show
Traceback (most recent call last):

  File "<ipython-input-9-7e447e99829e>", line 1, in <module>
    lgb.plot_tree(clf)

  File "C:\Users\Guo\Anaconda3\lib\site-packages\lightgbm\plotting.py", line 450, in plot_tree
    s.write(graph.pipe(format='png'))

AttributeError: 'Digraph' object has no attribute 'pipe'

would u give me suggestions?

**Comment by StrikerRUS** [comment]
Hmmm... Can you please run `create_tree_digraph` instead of `plot_tree`, as you did previously?

**Comment by Twinkle123321** [comment]
create_tree_digraph works,I'm so excited!,I also noticed that "It is preferable to use create_tree_digraph()"thank you very much!

**Comment by StrikerRUS** [comment]
Got it! Glad that you are able to run `create_tree_digraph` at least!

Please give me some time to figure out why the error with `plot_tree` happens. As I've already said, full script (and source data, if it isn't sensitive) will help a lot.

**Comment by Twinkle123321** [comment]
ok,Can I pack them to  your e-mail?

**Comment by StrikerRUS** [comment]
Yeah, sure!

nekit94-08 (at) mail (dot) ru

**Comment by StrikerRUS** [comment]
Can you please also attach the output of the `conda list` command?

**Comment by Twinkle123321** [comment]
I run the examples you gave above,it has same error,so I check the packages's version  you list,found my Graphviz Python wrapper from PyPI's version is 0.3.3,after upgrading to 0.10.1 ,"plot_tree" finally works,thank you fvery much for your patience and timely suggestions!

**Comment by StrikerRUS** [comment]
Happy that your problem is solved now!
