### ISSUE TITLE
prerelease package v3.1.2 broken

### ISSUE THREAD

**Issue by akstrfn** [microsoft/LightGBM#3667]
```bash
$ wget https://github.com/microsoft/LightGBM/archive/v3.1.2.zip
$ unzip unzip v3.1.2.zip && cd LightGBM-3.1.2
$ cmake -H. -Bbuild && cmake --build build

... snip ...

 /tmp/LightGBM-3.1.2/include/LightGBM/utils/common.h:35:10: fatal error: ../../../external_libs/fmt/include/fmt/format.h: No such file or directory
   35 | #include "../../../external_libs/fmt/include/fmt/format.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Likely the change introduced in PR #3639 requires change of workflow when making the release package.

**Comment by StrikerRUS** [comment]
We are so sorry, but that "release" was accidental! There are no plans to make `3.1.2` release actually. Next release should be `3.2.0` later. For now please keep using `3.1.1` or latest commits from the `master` branch.
