### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'example_case'

### ISSUE THREAD

**Issue by masafumimori** [microsoft/LightGBM#5791]
## Description
I got the error `TypeError: __init__() got an unexpected keyword argument 'example_case'` when using example_case parameter on plot_tree.

## Reproducible example
1: traing lightgbm model
2: run below:
```python
lgb.plot_tree(model, figsize=(30,30), example_case=x.iloc[:1,:], show_info=["split_gain"])
plt.show()
```
## Environment info
lightgbm  3.3.5

## Additional Comments
i see the parameter described on the doc [here](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.plot_tree.html)
but it gives me the error and couldnt find anyone else having the same issue... Maybe i'm doing it wrong....

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

That feature was introduced in #5119, which has not made it into a release yet. The docs you're looking at at https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.plot_tree.html refer to the state of this project on its `master` branch.

To view the docs for the latest release, choose a version from the bottom left navigation. For example, for v3.3.5: https://lightgbm.readthedocs.io/en/v3.3.5/pythonapi/lightgbm.plot_tree.html.

To use this functionality, you can install the Python package from source, following the instructions in https://github.com/microsoft/LightGBM/blob/master/python-package/README.rst.

Sorry for the confusion.

**Comment by masafumimori** [comment]
@jameslamb 
Fantastic! Thank you for your answer.

I thought 3.3.5 was the latest and so I was a bit confused...
Thanks for your help again!

**Comment by jameslamb** [comment]
No problem! Sorry for the confusion, it's happened to other people too. We'llook into ways to make this clearer (and try to release the last year+ of changes soon!)
